name: curve-burners
contracts_folder: contracts/

plugins:
  - name: vyper
  - name: alchemy
  - name: hardhat
  - name: ledger
  - name: etherscan
  - name: arbitrum
  - name: optimism
  - name: polygon

default_ecosystem: ethereum

# vyper:
#   evm_version: paris  # enable for non PUSH0 evm networks

hardhat:
  hardhat_config_file: ./hardhat.config.js
  fork:
    ethereum:
      mainnet:
        upstream_provider: alchemy

ethereum:
  default_network: mainnet-fork
  mainnet_fork:
    transaction_acceptance_timeout: 99999999
    default_provider: hardhat
  mainnet:
    transaction_acceptance_timeout: 99999999

test:
  mnemonic: test test test test test test test test test test test junk
  number_of_accounts: 5
